In [1]:
import numpy as np
from sklearn import preprocessing

In [7]:
# method 1 : Cant apply scale to incoming test datasets
# cant extract parameters
x = [[0,3],[9,4],[1,1],[2,7]]

x_scaled = preprocessing.scale(x)


print(x_scaled)
print(x_scaled.sum())
print(x_scaled.mean())
print(x_scaled.std())

[[-0.84852814 -0.34641016]
 [ 1.69705627  0.11547005]
 [-0.56568542 -1.27017059]
 [-0.28284271  1.5011107 ]]
0.0
0.0
1.0


In [9]:
# method 2 : We will be able to apply scale to incoming datasets
# Types of scalers present 
# a) Standard : mean = 0, variance =1 (by default)
# b) minMax Scaler : 0,1 (by default)
# c) absoluteMax Scaler
# Note : Default values can be changed (passed as parameters)

scaler = preprocessing.StandardScaler()
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
scaler.transform(x)

array([[-0.84852814, -0.34641016],
       [ 1.69705627,  0.11547005],
       [-0.56568542, -1.27017059],
       [-0.28284271,  1.5011107 ]])

In [12]:
scaler.transform([[1,2],[3,4]]) # Scales according to parameters calculated during fit command

array([[-0.56568542, -0.80829038],
       [ 0.        ,  0.11547005]])